'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CompSearchAll

    '''<summary>
    '''HyperLink_Finished control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink_Finished As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Label_TechnologyBuzzwords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_TechnologyBuzzwords As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBox_TechnologyBuzzwords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox_TechnologyBuzzwords As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GridView_SearcAllUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_SearcAllUsers As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlSearchAllUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlSearchAllUsers As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Button_SearchAllUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button_SearchAllUsers As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Label_FailureNotificationMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_FailureNotificationMessage As Global.System.Web.UI.WebControls.Label
End Class
