'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CompViewApps

    '''<summary>
    '''HyperLink_Finished control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink_Finished As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''GridView_CompanyViewApplicants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_CompanyViewApplicants As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlCompanyViewApplicants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCompanyViewApplicants As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Label_FailureNotificationMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_FailureNotificationMessage As Global.System.Web.UI.WebControls.Label
End Class
