'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CompUpdateOneJob

    '''<summary>
    '''HyperLink_Finish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink_Finish As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Label_CompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_CompanyName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBox_Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox_Title As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator_Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator_Title As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Label_Details control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Details As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBox_Details control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox_Details As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator_Details control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator_Details As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Label_Location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Location As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBox_Location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox_Location As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator_Location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator_Location As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Label_Salary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Salary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBox_Salary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox_Salary As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator_Salary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator_Salary As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Label_Benefits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Benefits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBox_Benefits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox_Benefits As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator_Benefits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator_Benefits As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Label_Hours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Hours As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBox_Hours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox_Hours As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator_Hours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator_Hours As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Label_StartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_StartDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBox_StartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox_StartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ScriptManager_OfferCountdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager_OfferCountdown As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''Timer_OfferCountdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Timer_OfferCountdown As Global.System.Web.UI.Timer

    '''<summary>
    '''UpdatePanel_OfferCountdownTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_OfferCountdownTitle As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Label_OfferCountdownTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_OfferCountdownTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_OfferCountdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_OfferCountdown As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonUpdateJobOffer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonUpdateJobOffer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonRenewJobOffer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonRenewJobOffer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Label_InactiveMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_InactiveMessage As Global.System.Web.UI.WebControls.Label
End Class
