'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CompanyServices

    '''<summary>
    '''HyperLink_UpdateCompanyDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink_UpdateCompanyDetails As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HyperLink_UploadJobOffer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink_UploadJobOffer As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HyperLink_UpdateJobOffer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink_UpdateJobOffer As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HyperLink_SearchUserDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink_SearchUserDetails As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HyperLink_ReviewApplicants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink_ReviewApplicants As Global.System.Web.UI.WebControls.HyperLink
End Class
