'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''HyperLink_UserLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink_UserLogin As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HyperLink_CompanyLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink_CompanyLogin As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''AdRotator_JobsIEAdverts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdRotator_JobsIEAdverts As Global.System.Web.UI.WebControls.AdRotator

    '''<summary>
    '''XmlDataSource_JobsIEAdverts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlDataSource_JobsIEAdverts As Global.System.Web.UI.WebControls.XmlDataSource
End Class
