'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UserUploadCV

    '''<summary>
    '''HyperLink_Finish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink_Finish As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''FileUpload_UserCV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload_UserCV As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''Button_UploadUserCV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button_UploadUserCV As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Label_UploadStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_UploadStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_CV_FileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_CV_FileName As Global.System.Web.UI.WebControls.Label
End Class
