'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UserSearchOffers

    '''<summary>
    '''HyperLink_Finished control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink_Finished As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Label_Technology control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Technology As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBox_Technology control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox_Technology As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label_Location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Location As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBox_Location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox_Location As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GridView_SearcJobOffers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_SearcJobOffers As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlSearchJobOffers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlSearchJobOffers As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Button_SearchJobOffers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button_SearchJobOffers As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Label_InactiveMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_InactiveMessage As Global.System.Web.UI.WebControls.Label
End Class
