'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UserViewOneOfTheJobsYouApplied

    '''<summary>
    '''HyperLink_Finished control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink_Finished As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Label_CompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents Label_CompanyName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_Location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents Label_Location As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents Label_Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_Details control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents Label_Details As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_Salary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents Label_Salary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_Benefits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents Label_Benefits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_Hours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents Label_Hours As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_OfferDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents Label_OfferDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_FailureNotificationMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents Label_FailureNotificationMessage As Global.System.Web.UI.WebControls.Label
End Class
