'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UserServices

    '''<summary>
    '''HyperLink_UpdateUserDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink_UpdateUserDetails As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HyperLink_UploadCV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink_UploadCV As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HyperLink_SearchJobOffers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink_SearchJobOffers As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HyperLink_ViewJobsAppliedFor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink_ViewJobsAppliedFor As Global.System.Web.UI.WebControls.HyperLink
End Class
